#
##
### by @aurelienmaury for @YesWeScale
##
#
heat_template_version: 2013-05-23

description: GlusterFS Distributed Replicated Cluster

parameters:

  server_image_id:
    description: Server image id (Debian Jessie expected)
    default: 670d1e98-844d-45d9-8f32-5cb45bd55d6f
    label: Server image id
    type: string

  public_network:
    description: Public network for Floating IP
    default: 6ea98324-0f14-49f6-97c0-885d1b8dc517
    label: Public network
    type: string

  keeper_keypair:
    description: Keepers' Keypair
    label: SSH Keypair
    type: string

  keeper_flavor:
    default: n2.cw.highmem-2
    description: Flavor of the Keeper server
    type: string
    label: Keeper Server Flavor
    constraints:
      - allowed_values:
          - s1.cw.small-1
          - n1.cw.standard-1
          - n1.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16
          - n2.cw.highmem-2

  datanode_keypair:
    description: Datanode's keypair
    label: SSH Keypair
    type: string

  datanode_flavor:
    default: n2.cw.highmem-2
    description: Flavor of the GlusterFS data nodes
    type: string
    label: Gluster Nodes Flavor
    constraints:
      - allowed_values:
          - s1.cw.small-1
          - n1.cw.standard-1
          - n1.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16
          - n2.cw.highmem-2

  local_cidr:
    default: "192.168.47.0/24"
    description: prefix of a class C cidr, less the ending .0/24
    type: string

  remote_cidr:
    default: 192.168.74.0/24
    description: complete cidr of the other side of the tunnel
    type: string

resources:
  network:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      cidr: { get_param: local_cidr }
      host_routes:
        - destination: { get_param: remote_cidr }
          nexthop: { "Fn::Replace": [ {'.0/24': '.254'}, {get_param: local_cidr} ] }
        - destination: 0.0.0.0/0
          nexthop: { "Fn::Replace": [ {'.0/24': '.1'}, {get_param: local_cidr} ] }
      allocation_pools:
        - start: { "Fn::Replace": [ {'.0/24': '.10'}, {get_param: local_cidr} ] }
          end: { "Fn::Replace": [ {'.0/24': '.249'}, {get_param: local_cidr} ] }

  router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      external_gateway_info:
        enable_snat: true
        network: "public"

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource : router }
      subnet_id: { get_resource : subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_network }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: network }
      fixed_ips:
        - ip_address: { "Fn::Replace": [ {'.0/24': '.254'}, {get_param: local_cidr} ] }
          subnet_id: { get_resource: subnet }
      security_groups: [{ get_resource: security_group }]

  keeper_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: ipsec_config }

  ipsec_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            echo "export LINKED_FLOATING_IP=$floating_ip$" >> /etc/profile.d/stack_vars.sh
            route del -net $site_b$
          params:
            $floating_ip$: { get_attr: [floating_ip, floating_ip_address] }
            $site_b$: { get_param: remote_cidr }

  keeper_server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keeper_keypair }
      image: { get_param: server_image_id }
      flavor: { get_param: keeper_flavor }
      networks:
        - port: { get_resource: server_port }
      user_data_format: RAW
      user_data:
        get_resource: keeper_init

  datanode1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: datanode_keypair }
      image: { get_param: server_image_id }
      flavor: { get_param: datanode_flavor }
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }

  datanode2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: datanode_keypair }
      image: { get_param: server_image_id }
      flavor: { get_param: datanode_flavor }
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }

  datanode3:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: datanode_keypair }
      image: { get_param: server_image_id }
      flavor: { get_param: datanode_flavor }
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }

  datanode4:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: datanode_keypair }
      image: { get_param: server_image_id }
      flavor: { get_param: datanode_flavor }
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }

  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: keeper_server }

outputs:
  floating_ip:
    description: Keeper public IP address
    value: { get_attr: [floating_ip, floating_ip_address] }
