#
##
### @YesWeScale
##
#
heat_template_version: 2013-05-23


description: Prod-like infrastructure setup for glusterfs


parameters:
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string

  flavor_name:
    default: s1.cw.small-1
    description: Flavor to use for the deployed instance
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - s1.cw.small-1
          - n1.cw.standard-1
          - n1.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16

  debian_jessie_image_id:
    type: string
    default: 168f7c6b-20a6-4a4e-8052-d1200aa36a1e

resources:
  admin_network:
    type: OS::Neutron::Net

  data_network:
    type: OS::Neutron::Net

  admin_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: admin_network }
      ip_version: 4
      cidr: 10.42.42.0/24
      allocation_pools:
        - { start: 10.42.42.10, end: 10.42.42.199 }

  data_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: data_network }
      ip_version: 4
      cidr: 10.1.1.0/24
      allocation_pools:
        - { start: 10.1.1.10, end: 10.1.1.199 }

  router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      external_gateway_info:
        enable_snat: true
        network: "public"

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource : router }
      subnet_id: { get_resource : data_subnet }

  admin_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource : router }
      subnet_id: { get_resource : admin_subnet }

  admin_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }

  data_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - direction: ingress
          remote_mode: remote_group_id
          remote_group_id: { get_resource: admin_security_group }

  admin_server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: admin_network }
      fixed_ips:
        - { ip_address: 10.42.42.254, subnet_id: { get_resource: admin_subnet } }
      security_groups: [{ get_resource: admin_security_group }]

  admin_server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: 168f7c6b-20a6-4a4e-8052-d1200aa36a1e
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: admin_server_port }

  data_server_1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: 168f7c6b-20a6-4a4e-8052-d1200aa36a1e
      flavor: { get_param: flavor_name }
      networks:
        - network: { get_resource: data_network }
      security_groups:
        - { get_resource: data_security_group }

  data_server_2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: 168f7c6b-20a6-4a4e-8052-d1200aa36a1e
      flavor: { get_param: flavor_name }
      networks:
        - network: { get_resource: data_network }
      security_groups:
        - { get_resource: data_security_group }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: admin_server }

outputs:
  floating_ip:
    description: Admin zone entry point
    value: { get_attr: [floating_ip, floating_ip_address] }
