---
- name: common aliases
  copy:
    dest=/etc/profile.d/ll.sh
    content="alias ll=\"ls -aul\""
    owner=root
    group=root
    mode=0644

- name: default sh is bash
  file:
    src=/bin/bash
    dest=/bin/sh
    state=link

- name: host is up-to-date
  apt:
    upgrade=full
    update_cache=yes

- name: ntpdate is absent
  apt:
    pkg=ntpdate
    state=absent
    purge=yes

- name: ntp is present
  apt:
    pkg=ntp
    state=present

- name: ntp is configured
  template: src=ntp-client.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: ntp is enabled
  service:
    name=ntp
    state=started
    enabled=yes

- name: gluster repositories key trusted
  apt_key:
    url='http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/pub.key'
    state=present

- name: gluster repositories listed
  apt_repository:
    repo='deb http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/Debian/jessie/apt jessie main'
    state=present
    update_cache=yes
