---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- name: common aliases
  copy:
    dest=/etc/profile.d/aliases.sh
    content="alias ll=\"ls -aul\""
    owner=root
    group=root
    mode=0644

- name: default sh is bash
  file: src=/bin/bash dest=/bin/sh state=link

- name: packages installed
  apt: pkg=aptitude state=present

- name: apt-get update & upgrade
  apt: update_cache=yes upgrade=full

- name: base toolkit
  apt: pkg="{{ item }}" state=present
  with_items:
    - tmux
    - tcpdump
    - lsof
    - vim
