---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- name: common aliases
  copy:
    dest=/etc/profile.d/ll.sh
    content="alias ll=\"ls -aul\""
    owner=root
    group=root
    mode=0644

- name: default sh is bash
  file: src=/bin/bash dest=/bin/sh state=link

- name: ntpdate is absent
  apt:
    pkg=ntpdate
    state=absent
    purge=yes

- name: base toolkit
  apt: pkg="{{ item }}" state=present
  with_items:
    - tmux
    - tcpdump
    - lsof
    - vim
    - ntp

- name: ntp is configured
  template: src=ntp-client.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: ntp is enabled
  service:
    name=ntp
    state=started
    enabled=yes

- name: gluster repositories key trusted
  apt_key:
    url='http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/pub.key'
    state=present

- name: gluster repositories listed
  apt_repository:
    repo='deb http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/Debian/jessie/apt jessie main'
    state=present
    update_cache=yes
