---
- name: gluster repositories key trusted
  apt_key:
    url='http://download.gluster.org/pub/gluster/glusterfs/3.6/3.6.6/Debian/jessie/pub.key'
    state=present

- name: gluster repositories listed
  apt_repository:
    repo='deb http://download.gluster.org/pub/gluster/glusterfs/3.6/3.6.6/Debian/jessie/apt jessie main'
    state=present
    update_cache=yes

- name: gluster is installed
  apt:
    name={{ item }}
    state=present
  with_items:
    - glusterfs-client
