- hosts: site_a
  become: yes

  tasks:
    - name: get public key from site A
      fetch:
        src='/home/cloud/.ssh/id_rsa_georep.pub'
        flat=yes
        dest='./'

- hosts: site_b
  become: yes

  tasks:
    - name: inject public key from site A into site B
      copy:
        src='./id_rsa_georep.pub'
        dest='/home/cloud/keeper-toolkit/'

    - name: inject public key from site A into site B
      copy:
        src='/home/cloud/keeper-toolkit/data_nodes_ssh_config'
        dest='/home/cloud/keeper-toolkit/'