---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- name: packages installed
  apt: pkg={{ item }} state=present
  with_items:
    - strongswan
  tags: init

- name: configuration files uploaded
  template:
    src="{{ item.file }}"
    dest="{{ item.path }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - { file: "etc_ipsec.conf.j2",    path: "/etc/ipsec.conf"    }
    - { file: "etc_ipsec.secrets.j2", path: "/etc/ipsec.secrets" }
    - { file: "strongswan.conf.j2", path: "/etc/strongswan.conf" }

- name: ipv4 forwarding is enabled
  sysctl:
    name="net.ipv4.ip_forward"
    value=1
    sysctl_set=yes
    state=present
    reload=yes

- name: ansible installed
  pip: name=ansible state=latest
